### ISSUE TITLE
Missing options for --net and --ip

### ISSUE THREAD

**Issue by Nurza** [bcicen/docker-replay#4]
Hello, you are doing a great job, thank you for this tool!

But the docker run options --net and --ip are missing ;)

**Comment by Nurza** [comment]
And, it is possible to you to detect if a container is running with the detached (-d) option?

**Comment by bcicen** [comment]
`--net` has been added in the [latest release](https://github.com/bcicen/docker-replay/releases/latest)

**Comment by bcicen** [comment]
`--ip` option is already included, if explicitly passed during container creation
