### ISSUE TITLE
docker-replay generates both --hostname and --uts host options

### ISSUE THREAD

**Issue by jgoldschrafe** [bcicen/docker-replay#7]
When run against a container that was started in `--uts host` mode, `docker-replay` will generate a command line that contains both the `--hostname` and `--uts host` arguments. These options to the Docker CLI are incompatible and attempting to specify a hostname when running with `--uts host` will result in a fatal error.

**Comment by bcicen** [comment]
this is [fixed](https://github.com/bcicen/docker-replay/commit/a09ba079c7b30a6b429776c6fb5a883ae430e5de) in the 1.5 release, now published on pypi
